### ISSUE TITLE
A visitor can do a basic search for articles, recipes, or cooking videos.

### ISSUE THREAD

**Issue by marcuschui2022** [marcuschui2022/comp231-008_team_9_F23#2]
- Search page (front-end)
  1. Input field(s) -> text-inputs and dropdown list
  2. List -> text only (google search result) or has image (Youtube search result ) 
  3. http(s) request -> JSON

- Search function(back-end)
  1. gateway(url) for request
  2. get data from database by request

**Comment by Zack0079** [comment]
- Search page (front-end)
